spring:
  application:
    name: anvilj
  profiles:
    active: dev #'@profile.name@'
  mustache:
    enabled: true
    prefix: classpath:/public/
    #prefix: classpath:/templates/
    suffix: .html
  servlet:
      expose-request-attributes: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml

frontend:
  locations: file:./dist/ # TODO
  #context-root: /anvilj/**

register:
  partner:
    orgCode: A03A01 # orgCode use id now, but should be path name easier readable,eg: anvilj.web
    roles: partner # role code list with comma, eg: partner,admin
  emailSign:
    durationSeconds:  1800 # 60 * 10
    endPoint: http://localhost:8181/anvilj