spring:
  application:
    name: anvilj
  profiles:
    active: dev #'@profile.name@'
  mustache:
    enabled: true
    prefix: classpath:/public/
    #prefix: classpath:/templates/
    suffix: .html
  servlet:
      expose-request-attributes: true

register:
  partner:
    roles: partner # role code list with comma, eg: partner,admin
  emailSign:
    durationSeconds:  1800 # 60 * 10
    endPoint: http://localhost:8181/anvilj